### ISSUE TITLE
SD2SNES Mode 7 Issues When "In Game Hook" Activated.

### ISSUE THREAD

**Issue by orange808** [VitorVilela7/SA1-Root#12]
Using the v1.1 patch on a USA 1 Chip SNES (UN10024312) together with a "standard" SD2SNES on firmware 1.10.3 with "In Game Hook" active.

The game will crash when displaying split screen two player Mode 7 after the camera rotates down to the ground, the player sprites appear, and gameplay should begin.

One player mode displays artifacts while playing Mode 7 stages, but remain playable.

Deactivating "In Game Hook" resolves the issues.

**Comment by VitorVilela7** [comment]
In game hookes can sometimes generate undefined behavior which cannot be controlled on the game side, so there is nothing that can be done other than looking for SD2SNES improvement updates which makes the hooks less unstable for certain games.
