### ISSUE TITLE
Would games that use enhancement chips benefit from it?

### ISSUE THREAD

**Issue by psyalemao** [VitorVilela7/SA1-Root#14]
Hello,
I wonder if games that use enhancement chips like CX4, the DSP's, SuperFx could take advantage from it? I mean calling the SA-1 first instead of the main snes CPU and if required making the SA-1 call the main cpu later?

Looking forward for super mario all-stars + super mario world, zelda link to the past, super metroid patches
I was thinking to start to make a no-intro romset of SA-1 optimized roms if more patches get surged and if I remember some people did it for MSU-1 roms.

Thanks in advance for your hard work with the SA-1. Already tested the SA-1 Pack on SMW and worked great so far! Best regards.

**Comment by VitorVilela7** [comment]
CX4 and Super FX: requires rewriting code to use the SA-1 chip, not trivial. Would require more work than it's worth.
DSP-1: possible, by transferring the work to SA-1 side. Still requires a lot of work.
