### ISSUE TITLE
Rompatcher on your site

### ISSUE THREAD

**Issue by Aisyk** [VitorVilela7/SA1-Root#18]
Hi,

Thanks for your work, i'd like to share you this tool, to be implemented on a website (very simple to install it).
https://github.com/marcrobledo/RomPatcher.js/

(i'm not the author of this tool)
Take a look ;)

**Comment by VitorVilela7** [comment]
Looks like it's already available at https://www.marcrobledo.com/RomPatcher.js/, it's a reasonable option, I've added it to https://sneslab.net/wiki/How_to_apply_ROM_patches
