### ISSUE TITLE
Gradius III USA pre-patching SHA256 hash is missing a hex digit

### ISSUE THREAD

**Issue by XT-8147** [VitorVilela7/SA1-Root#26]
When verifying my USA ROM of Gradius III before patching, I noticed that the SHA256 hash provided for verification only has 63 hexadecimal digits.  Comparing the provided hash with the hash of my ROM, it seems to be missing the very last digit.

**Provided SHA256 hash (before patching):** 93DA752A0C76167D0907EFA832367E5D14AAB8E835B864F345C386071A9AF71
**My ROM's SHA256 hash (before patching):** 93DA752A0C76167D0907EFA832367E5D14AAB8E835B864F345C386071A9AF718

After patching, the patched ROM matched the expected post-patching SHA256 hash, so no problems there.

I've patched each game (with both the normal and Origin patches), checking the SHA256 hashes before and after patching, and didn't notice this issue with any of the other provided hashes for USA ROMs.

**Comment by thingsiplay** [comment]
I am here for the same reason. Last digit is missing, probably a copy/paste error with mouse.

**Comment by VitorVilela7** [comment]
Thank you for the bug report. I completely missed this. Fixed.
