### ISSUE TITLE
Message before playing..

### ISSUE THREAD

**Issue by gmoqa** [VitorVilela7/SA1-Root#29]
Would it be possible to add a message at the beginning of the games saying that this does not represent the original version of the game? gameplays of these versions are becoming more and more popular that could affect the perception of the platform in the future.

I guess this topic has been touched on before but I didn't find anything.

Thank you for your great work ❤️

Saludos.

**Comment by JoshuaPettus** [comment]
1. There are 1000s of rom hacks with many of them being immensely popular and widespread.   I fail to see how throwing an annoying banner over a few is going to solve your problem.

2.  Whose perception are you worried for exactly, what harm are you trying to prevent, and how exactly would this stop the harm?   If one went through the trouble of hacking the rom, I'd assume one would be aware he hacked the rom.   If you were concerned about some youtuber showing footage of a rom hack, and not disclosing that he used a rom hack (which I would argue is a problem that doesn't really exist) , would the youtuber even necessarily show the beginning banner?

**Comment by VitorVilela7** [comment]
I understand the concerns about the legitimacy of certain gameplays of my ROM hacks. Unfortunately, I don't think there's any action that can be made to mitigate that. Adding a message before playing can be easily cut or hidden from the gameplay video and still people can alter the gameplay attributes by overclocking the emulator or even changing internal speed values through cheat codes or hex-edits.

As a suggestion, consider asking the video authors for transparency about what version they're playing when you see such occurrences.

About this issue, I don't think there's any action I can do given the context I just explained, so I'm closing this issue.
