### ISSUE TITLE
desync issue with Race Drivin'

### ISSUE THREAD

**Issue by dinkc64** [VitorVilela7/SA1-Root#32]
Hi @VitorVilela7 
I'm working on a snes emulator with sa-1, and have 2 issues with Race Drivin'.  I've spent weeks trying to solve this, but, with no luck. This is why I ask for your guidance :)
When the demo game starts, the race de-syncs.  For example:
x Going down the first jump, car appears to go "below" the road, then pop back onto the road
x On first turn, car turns too late, and hits the house

I make sure:
run 1 cycle for every read/write on the SA-1 bus.  2 cycles for accesses to BW-RAM (just like your fixes for snes9x)
If I enable or disable contention cycles on rom/bwram/iram, it makes no difference

Well, maybe you have an idea what might cause these symptoms with your game :)  The original non-sa1 game runs fine, as well as every game in the snes library... (including SA1-enabled Parodius & Contra III)

best regards,
- dink

**Comment by dinkc64** [comment]
Oops, nevermind - the problem is my fault. Explanation:
I ran the

**Comment by dinkc64** [comment]
nevermind, it was a mixup between base/origin versions...

**Comment by VitorVilela7** [comment]
Hey @dinkc64, it's really nice to see you are creating an emulator.

If that helps you on the future, there is a SNES speed test available where
you can compare the speed measured against different systems:
https://github.com/VitorVilela7/SnesSpeedTest

It also measures the SA-1 internal speed.

Em qua., 7 de ago. de 2024 às 22:10, dinkc64 ***@***.***>
escreveu:

**Comment by dinkc64** [comment]
Hi @VitorVilela7!
Thanks for the tip, I've gotten all the speeds to match on the 4 screens except these 2 on the first screen:
HDMA ROM   ROM
DMA ROM     ROM

I'll keep trying :)
