### ISSUE TITLE
Snes and sa-1 accessing the same function in gradius causing slowdown and glitchy graphics 

### ISSUE THREAD

**Issue by slidelljohn** [VitorVilela7/SA1-Root#4]
Hello vitor! I fixed the glitchy graphics and the slowdown when the bosses die when the screen is disappearing in gradius. I’m surprised no one notices the glitchy graphics. You have the snes and sa-1 accessing that same function. Just nop that function on the snes side and it’s fixed. I also created a patch for it with a optimization for that function to make it around %15 faster.

**Comment by VitorVilela7** [comment]
Hi slidelljohn! I was aware of that issue but I didn't have enough time to investigate it. I'm glad that you figured it out and ouch... it runs twice?! That might explain the v-blank overflow hahahahha

Feel free to make a pull request and I'll merge it

**Comment by slidelljohn** [comment]
I don’t really know how to use GitHub yet and I don’t know what a pull request is but I’ll learn eventually. I posted the information on my projects page on romhacking.net. Congratulations on the sa-1 stuff it’s really impressive. I was also doing a sa-1 gradius 3 hack not just the fastrom but I haven’t finished it yet. It’s also posted on my projects page.

**Comment by VitorVilela7** [comment]
Ahh I see... Feel free to copy/paste the code changes you did it here and I'll apply it myself.

Also thank you!

**Comment by slidelljohn** [comment]
Just nop the jsl at $00:82b2 to turn that function off on the snes side and it’s fixed.

**Comment by VitorVilela7** [comment]
Thanks, it's been fixed on version 1.5!

Let me know if it works

**Comment by slidelljohn** [comment]
Your welcome vitor! I tested the patch and it looks like it’s working right.
