### ISSUE TITLE
Is possible add 4 extra difficulties?

### ISSUE THREAD

**Issue by CristianCG86** [VitorVilela7/SA1-Root#6]
Hi!!

Is posible to adds the 4 extra difficulties (elite, master, expert and pro)?
In this patch it was added [http://www.romhacking.net/forum/index.php?topic=27609.0](url)

Thanks!!

**Comment by slidelljohn** [comment]
Yes it’s possible. I created that patch. I’m pretty sure Vitor’s official sa-1 optimization isn’t going to include any hacks like that inside of it but someone could add it in when I finish writing and uploading the docs for it.

**Comment by VitorVilela7** [comment]
Pretty much what slidelljohn said. This is not a bad idea, but the focus for SA-1 Root is keeping the game close as the original. However nothing avoids you from i.e. applying SA-1 Root version and then apply slidelljohn patch (assuming it's modified to accept the SA-1 Root version) and then you will have both of the best worlds together. Who knows? :D
