### ISSUE TITLE
add hash values for target ROMs

### ISSUE THREAD

**Issue by frederic-mahe** [VitorVilela7/SA1-Root#7]
Hi Vitor,

awesome work on the these patches. For *Gradius* and future SA1-ed games, it might be interesting to mention hash values for the ROMs that should be patched, and for the ROMs after patches have been applied.

For instance, here are the hash values for *Gradius III* (USA) ([source](https://datomatic.no-intro.org/?page=show_record&s=49&n=0982)):
```
CRC32: CD973979
MD5: EA30C4F341F6B7A6E290699460BA6C51
SHA-1: 7E62203A4198E9404EB7B076802C09786E5A63F4
```
And if I am not mistaken, applying the latest SA1 patch should produce a ROM with the following hash value (case is irrelevant):
```
MD5: 6b79ec4484338b8a5715100fafda9a08
```
Mentioning these hash values on this repository would help people avoid bad ROMs, and be sure that they applied the patch correctly.

Thanks

**Comment by VitorVilela7** [comment]
Hi frederic! I have included the hashes for the output ROMs at https://github.com/VitorVilela7/SA1-Root/tree/master/Gradius-III#jpn-version, but I can add for the input ROM if needed.

**Comment by frederic-mahe** [comment]
My bad, I did not open the second README file. I would argue that having checksums for the input ROMs would make this documentation more complete. Up to you. Either way, please feel free to close that issue.

thanks,

**Comment by VitorVilela7** [comment]
Checksums added!
