### ISSUE TITLE
Issue loading on SD2SNES Pro

### ISSUE THREAD

**Issue by GerryHolt** [VitorVilela7/SA1-Root#8]
Wasn't sure where to put this issue, so I figured I'd post it here as well as on the sd2snes forums. I purchased a sdspro and am running it on a super famicom. I've checked both the pre-patched and post-patched hashes against what's in the read me and they match. 

Unfortunately, the game won't go past the white grid on load. It will just sit there. I've heard this run fine on the regular SD2SNES and I've tested my rom on various emulators and it runs fine. I've so far not had any issues with other SA-1 games on my pro so I figured I'd drop a line here and see if anyone else has had this issue or if there's something you might know about it.

**Comment by GerryHolt** [comment]
I discovered this seems to be an issue when using the USB2SNES 1.10.3 firmware (firmware.im3 and fpga_base.bi3) on the SD2SNES Pro. When reverting back to standard 1.10.3 firmware, it worked fine.

**Comment by VitorVilela7** [comment]
Glad to hear it was solved! I believe it was causing some interference on the interrupts which probably affects the way Gradius 3 engine runs the game.
